### ISSUE TITLE
Could we add back the dependency on zope.cachedescriptors?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.container#16]
This package duplicates `readproperty` and `Lazy`, without some of their newer bug fixes/enhancements.

zope.cachedescriptors has no dependencies other than setuptools.

I see that this dependency was removed back in 2009. I understand the desire to minimize dependencies, but I also see the benefit to sharing the implementation of such things, especially when they are as low-level as non-data descriptors.

Thoughts?

**Comment by icemac** [comment]
+1 for adding this dependency again as it is light-weight and code duplication causes problems we do not want to have.
