### ISSUE TITLE
OrderedContainer.updateOrder corrupts keys

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.container#21]
It doesn't ensure the incoming keys are text, leading to possible corruption. Here's Python 2:
```pycon
>>> from zope.container.ordered import OrderedContainer
>>> oc = OrderedContainer()
>>> oc['a'] = 1
>>> oc['b'] = 2
>>> oc.keys()
[u'a', u'b']
>>> oc.updateOrder(('b', 'a')) # Note the bytes
None
>>> oc.keys() # Unicode is gone!
['b', 'a'] 
```

Python 3 fails:
```pycon
>>> c.updateOrder((b'b', b'a',))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//lib/python3.6/site-packages/zope/container/ordered.py", line 285, in updateOrder
    raise ValueError("Incompatible key set.")
ValueError: Incompatible key set.
```

I think it should either run the new keys through the same name conversion that happens in `__setitem__` OR it should not accept non-unicode keys.

I encountered this in `zope.copypastemove` tests.

Thoughts?

**Comment by tseaver** [comment]
Monte, give me 'door number 1" (normalize the names the same way `__setitem__` does).

**Comment by jamadden** [comment]
That'd be my vote too. It may need some minor refactoring to make it happen, but it shouldn't be too bad.
