### ISSUE TITLE
Can we make zope.container conditional dependent on zope.publisher ?

### ISSUE THREAD

**Issue by bloodbare** [zopefoundation/zope.container#7]
I'm using zope.container but with my own publisher and I'm not loading zope.publisher.

It would be possible to add an extras_requires with 'browser' to load zope.publisher and zope.traversing and a zcml condition to load browser related adapters ?

@tseaver if it brings problems its not a big deal, its just I'm loading zope.publisher and zope.traversing without using them.

**Comment by tseaver** [comment]
The `zope.publisher` and `zope.traversing` dependencies are needed for the `zope.container.traversal` module: it might be simpler to move that one module, plus the ZCML for it, into a separate project ('zope.containertraversal`), and then add a `traversal` extra which depended on it.   We could leave behind backward-compatibility imports in a stub `zope.container.traversal` module.

@hannosch, @agroszer, @mgedmin, @jamadden WDYT?

**Comment by jamadden** [comment]
I would tend to consider basic traversing (`ITraversable `) to be an important part of why zope.container exists, so a dependency on `zope.traversing` seems warranted to me. 

I don't feel the same way about `IBrowserPublisher` and `IXMLRPCPublisher` and wouldn't object to them being factored out, but then again, I don't use them or `zope.publisher`, so I'm biased there.

On the gripping hand, though, those two projects don't need a C compiler and don't pull in many (if any) dependencies that aren't already included in `zope.container`, so from my perspective the benefits of splitting out an additional library are very small, perhaps small enough to be bumping into the law of diminishing returns.

So I guess I would be -1 for removing `zope.traversing` support and -0 for removing `zope.publisher` support.
